// Generated by GraphWalker (http://www.graphwalker.org)
package com.company;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/company/CreateUserModel.json")
public interface CreateUserModel {

    @Edge()
    void e_InputCorrectCredentials();

    @Vertex()
    void v_ClientPage();

    @Edge()
    void e_OpenCreateUserPage();

    @Edge()
    void e_OpenUserPage();

    @Edge()
    void e_Close();

    @Vertex()
    void v_LoginPage();

    @Edge()
    void e_OpenLoginPage();

    @Edge()
    void e_Cancel();

    @Vertex()
    void v_SuccessCreateUser();

    @Vertex()
    void v_UserPage();

    @Edge()
    void e_InputEmptyData();

    @Vertex()
    void v_CreateUserPage();

    @Vertex()
    void v_AlertIncorrectData();

    @Vertex()
    void v_AlertEmptyData();

    @Edge()
    void e_InputIncorrectData();

    @Edge()
    void e_InputCorrectData();
}
