// Generated by GraphWalker (http://www.graphwalker.org)
package com.company;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/company/CreateSubscriptionModel.json")
public interface CreateSubscriptionModel {

    @Vertex()
    void v_SuccessCreateSubscription();

    @Edge()
    void e_OpenSubscriptionPage();

    @Edge()
    void e_InputCorrectCredentials();

    @Vertex()
    void v_ClientPage();

    @Edge()
    void e_Close();

    @Vertex()
    void v_LoginPage();

    @Edge()
    void e_OpenLoginPage();

    @Edge()
    void e_Cancel();

    @Edge()
    void e_InputEmptyData();

    @Vertex()
    void v_AlertIncorrectData();

    @Vertex()
    void v_CreateSubscriptionPage();

    @Vertex()
    void v_AlertEmptyData();

    @Vertex()
    void v_SubscriptionPage();

    @Edge()
    void e_OpenCreateSubscriptionPage();

    @Edge()
    void e_InputIncorrectData();

    @Edge()
    void e_InputCorrectData();
}
