// Generated by GraphWalker (http://www.graphwalker.org)
package com.company;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/company/CreateOutletModel.json")
public interface CreateOutletModel {

    @Edge()
    void e_InputCorrectCredentials();

    @Vertex()
    void v_CreateOutletPage();

    @Vertex()
    void v_ClientPage();

    @Edge()
    void e_Close();

    @Vertex()
    void v_LoginPage();

    @Edge()
    void e_OpenLoginPage();

    @Edge()
    void e_Cancel();

    @Edge()
    void e_OpenOutletPage();

    @Edge()
    void e_InputEmptyData();

    @Vertex()
    void v_CreateOutletSuccess();

    @Vertex()
    void v_AlertIncorrectData();

    @Edge()
    void e_OpenCreateOutletPage();

    @Vertex()
    void v_AlertEmptyData();

    @Vertex()
    void v_OutletPage();

    @Edge()
    void e_InputIncorrectData();

    @Edge()
    void e_InputCorrectData();
}
