// Generated by GraphWalker (http://www.graphwalker.org)
package com.company;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/company/LoginModel.json")
public interface LoginModel {

    @Edge()
    void e_OpenLoginPage();

    @Edge()
    void e_InputCorrectCredentials();

    @Edge()
    void e_OpenLogoutPage();

    @Vertex()
    void v_LogoutPage();

    @Vertex()
    void v_ClientPage();

    @Edge()
    void e_Logout();

    @Edge()
    void e_InputEmptyCredentials();

    @Vertex()
    void v_LoginPage();

    @Edge()
    void e_InputIncorrectCredentials();
}
